const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./router.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [{
    "name": "Endpoints",
    "description": "User and Product endpoints"
  }],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account"
      }
    }
  },
  definitions: {
    User: {
      id: 1,
      name: "Fulano de Tal",
      profession: "Administrador",
      birthDate: "1980-09-29",
      documentNumber: "01234567890",
      address: {
        zipCode: "42800049",
        street: "Rua Costa Pinto",
        number: 254,
        complement: null,
        neighborhood: "Centro",
        city: "Camaçari",
        state: "BA"
      },
      contact: {
        phone: "11985476932",
        email: "email@email.com"
      }
    },
    Product: {
      id: 1,
      name: "Smartphone Sony",
      categoryId: 1,
      price: 1000,
      quantity: 10
    }
  }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app")
});